services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: tail
    command:
      - -f
      - /dev/null
    volumes:
      - .:/sqldef-d1-test:cached
    ports:
      - 8787:8787
